# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifag', '0002_ifag_inicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationApprove',
            fields=[
            ],
            options={
                'verbose_name': 'cotação',
                'verbose_name_plural': 'aprovar cotações',
                'proxy': True,
                'indexes': [],
            },
            bases=('ifag.quotation',),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation', to='ifag.City', verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifag.Indicator', verbose_name='indicador econômico'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifag.Source', verbose_name='fonte'),
        ),
    ]
