# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifag', '0003_auto_20170901_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifag.City', verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='history',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifag.Indicator', verbose_name='indicador econômico'),
        ),
    ]
