# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ifag', '0005_auto_20170911_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='variation',
            field=models.DecimalField(decimal_places=2, default=0,
                                      max_digits=7, verbose_name='variação'),
        ),
    ]
