# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 16:24
from __future__ import unicode_literals

from django.db import migrations, models


def update_status(apps, schema_editor):
    """
    Atualiza o novo campo criado
    """
    Quotation = apps.get_model('ifag', 'Quotation')
    for entity in Quotation.objects.all():
        entity.status = 'approved' if entity.approved else 'waiting'
        entity.save()


class Migration(migrations.Migration):
    dependencies = [
        ('ifag', '0006_history_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='status',
            field=models.CharField(default='waiting', max_length=8,
                                   verbose_name='Status'),
        ),
        migrations.RunPython(update_status),
    ]
