# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ifag', '0007_add_quotation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='approved',
        ),
    ]
