# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 22:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ifag', '0009_add_change_approved_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, verbose_name='data')),
                ('create_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Publicação de Histórico',
                'verbose_name_plural': 'Publicações de Históricos',
            },
        ),
        migrations.AlterField(
            model_name='history',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='ifag.City', verbose_name='cidade'),
        ),
    ]
